################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cec.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_comp.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_crc.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_crc_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cryp.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cryp_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dac.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dac_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dcmi.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dfsdm.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dfsdm_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma2d.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dsi.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dts.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_fdcan.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gfxmmu.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hash.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hash_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hcd.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hrtim.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2s.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2s_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_irda.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_iwdg.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_jpeg.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_lptim.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ltdc.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ltdc_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdios.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mmc.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mmc_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_nand.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_nor.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_opamp.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_opamp_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ospi.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_otfdec.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pssi.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_qspi.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ramecc.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rng.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rng_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sai.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sai_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sd.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sd_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sdram.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smartcard.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smartcard_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smbus.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spdifrx.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sram.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_swpmi.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart_ex.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_wwdg.c \
../libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_usb.c 

OBJS += \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cec.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_comp.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_crc.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_crc_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cryp.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cryp_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dac.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dac_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dcmi.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dfsdm.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dfsdm_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma2d.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dsi.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dts.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_fdcan.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gfxmmu.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hash.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hash_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hcd.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hrtim.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2s.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2s_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_irda.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_iwdg.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_jpeg.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_lptim.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ltdc.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ltdc_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdios.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mmc.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mmc_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_nand.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_nor.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_opamp.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_opamp_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ospi.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_otfdec.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pssi.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_qspi.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ramecc.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rng.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rng_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sai.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sai_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sd.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sd_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sdram.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smartcard.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smartcard_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smbus.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spdifrx.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sram.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_swpmi.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart_ex.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_wwdg.o \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_usb.o 

C_DEPS += \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cec.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_comp.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_crc.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_crc_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cryp.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cryp_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dac.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dac_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dcmi.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dfsdm.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dfsdm_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma2d.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dsi.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dts.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_fdcan.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gfxmmu.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hash.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hash_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hcd.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hrtim.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2s.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2s_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_irda.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_iwdg.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_jpeg.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_lptim.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ltdc.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ltdc_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdios.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mmc.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mmc_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_nand.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_nor.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_opamp.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_opamp_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ospi.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_otfdec.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pssi.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_qspi.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ramecc.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rng.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rng_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sai.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sai_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sd.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sd_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sdram.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smartcard.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smartcard_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smbus.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spdifrx.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sram.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_swpmi.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart_ex.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_wwdg.d \
./libraries/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_usb.d 


# Each subdirectory must supply rules for building sources it contributes
libraries/STM32H7xx_HAL_Driver/Src/%.o: ../libraries/STM32H7xx_HAL_Driver/Src/%.c
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DSOC_FAMILY_STM32 -DSOC_SERIES_STM32H7 -DUSE_HAL_DRIVER -DSTM32H747xx -DCORE_CM7 -I"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32\drivers" -I"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32\drivers\include" -I"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32\drivers\include\config" -I"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32\libraries\CMSIS\Device\ST\STM32H7xx\Include" -I"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32\libraries\CMSIS\Include" -I"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32\libraries\CMSIS\RTOS\Template" -I"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32\libraries\STM32H7xx_HAL_Driver\Inc" -I"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32\libraries\STM32H7xx_HAL_Driver\Inc\Legacy" -I"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32" -I"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32\applications" -I"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32" -I"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32\rt-thread\components\drivers\include" -I"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32\rt-thread\components\finsh" -I"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32\rt-thread\components\libc\compilers\common" -I"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32\rt-thread\include" -I"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32\rt-thread\libcpu\arm\common" -I"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32\rt-thread\libcpu\arm\cortex-m7" -include"C:\Users\Mja\Documents\EMECS\PoliTO\Operating systems for embedded systems\Project\EOS_project\STM32\rtconfig_preinc.h" -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

